### ISSUE TITLE
Weapon image in chatroll message-content is not showing up due to trailing /

### ISSUE THREAD

**Issue by yjeroen** [pwatson100/symbaroum#112] opened 2021-02-23 19:06 UTC
Chat roll html of the damage, adds a / behind the weapon image src:
![image](https://user-images.githubusercontent.com/1303988/108894414-89e66a00-7612-11eb-84b6-67a31e603885.png)

Results in an unfound image:
![image](https://user-images.githubusercontent.com/1303988/108894429-8eab1e00-7612-11eb-9534-58b1038de0e3.png)

**Comment by yjeroen** [comment] 2021-02-23 19:09
Issue only shows up when hosting on s3, not on images hosted on the node foundry server, as that filesystem seems more restrict.

**Comment by pwatson100** [comment] 2021-02-23 19:12
Thank you for the clarification.  I expect it's because the image file name is mixed case and has spaces rather than "-".

**Comment by bithir** [comment] 2021-02-23 19:17
Confirmed code error - was not properly quoted, so included the end / for the html attribute. Resolved - merged to release testing.

**Comment by bithir** [comment] 2021-02-23 20:29
There will be some time before this is pushed to live, so @yjeroen if you want to perform the fix on your system in the meantime, let me know.

**Comment by yjeroen** [comment] 2021-02-23 20:43
@bithir, updated the file from #113, and I can confirm it solved the issue. :)

**Closed** 2021-03-28 12:22 UTC
Labels: bug
